# Generated by Django 4.0.5 on 2022-07-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_issues_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='assignee',
            new_name='assignee_user_id',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='author',
            new_name='author_user_id',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='project',
            new_name='project_id',
        ),
        migrations.AddField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'A faire'), ('IN PROGRESS', 'En cours'), ('CLOSED', 'Terminé')], default='TO_DO', max_length=128),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Elevée')], max_length=128),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('IMPROVEMENT', 'Amélioration'), ('TASK', 'Tâche')], max_length=128),
        ),
    ]
